const Countries = [
  { label: 'Afghanistan', value: 'AF' },
  { label: 'Bangladesh', value: 'BD' },
  { label: 'Brazil', value: 'BR' },
  { label: 'China', value: 'CN' },
  { label: 'Colombia', value: 'CO' },
  { label: 'Congo', value: 'CG' },
  { label: 'Cuba', value: 'CU' },
  { label: 'Ecuador', value: 'EC' },
  { label: 'Egypt', value: 'EG' },
  { label: 'Ethiopia', value: 'ET' },
  { label: 'Iran, Islamic Republic Of', value: 'IR' },
  { label: 'Iraq', value: 'IQ' },
  { label: 'Japan', value: 'JP' },
  { label: 'Mexico', value: 'MX' },
  { label: 'Palestinian Territory, Occupied', value: 'PS' },
  { label: 'Pakistan', value: 'PK' },
  { label: 'Panama', value: 'PA' },
  { label: 'Syrian Arab Republic', value: 'SY' },
  { label: 'Taiwan, Province of China', value: 'TW' },
  { label: 'Trinidad and Tobago', value: 'TT' },
  { label: 'Tunisia', value: 'TN' },
  { label: 'Venezuela', value: 'VE' },
  { label: 'Yemen', value: 'YE' },
  { label: 'Zimbabwe', value: 'ZW' },
];

export default Countries;
